name: fluro_pro
description: FluroPro is a null-safe Flutter routing library that adds flexible routing options like wildcards, named parameters and clear route definitions.
version: 2.0.5
homepage: https://github.com/InTheClodus/fluro_pro.git
repository: https://github.com/InTheClodus/fluro_pro.git

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
